config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "user/registrations"}
  root 'welcome#index'
  
  get 'my_portfolio', to: "users#my_portfolio"
  
  get 'search_stocks', to: "stocks#search"
  
  resources :user_stocks, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :friendships
  
  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/friends/_lookup.html.erb
<h1>My Friend</h1>
<h3>Search for Friends</h3>
<div id="friend-lookup">
    <%= form_tag search_friends_path, method: :get, remote: true, id: 'friend-lookup-form' do %>
        <div class="from-group row no-padding text-center col-md-12">
            <div class="col-md-10">
                <%= text_field_tag :search_param, params[:search_param], placeholder: "Enter name or email", autofocus: true, class: 'form-control search-box input-lg' %>
            </div>
            <div class="col-md-2">
                <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
                    <span class="fa fa-search"></span> Search
                <% end %>
            </div>
        </div>
    <% end %>
</div>
<div id="results">
    <%= render "users/result" %>
</div>

app/views/friends/_result.html.erb
<br><br><br>
<% if params[:action] == 'search' %>
<div class="result-block">
    <%= bootstrap_flash %>
</div>
<% end %>

<% if @users %>
    <% if @users.size > 0 %>
        <div id="friend-lookup-results" class="well results-block col-md-10">
            <table class="search-results-table col-md-12">
                <tbody>
                    <% @users.each do |user| %>
                        <tr>
                            <td><strong>Name: </strong> <%= user.full_name %></td>
                            <td><strong>Email: </strong> <%= user.email %></td>
                            <td><strong>Profile: </strong> 
                                <%= link_to "View Profile", user_path(user), class: "btn btn-xs btn-success"  %>
                                <% if current_user.not_friends_with?(user.id) %>
                                    <%= link_to "Add to Friend", add_friend_path(user: current_user, friend: user), class: "btn btn-xs btn-success", method: :post  %>
                                <% else %>
                                    <span class="label label-primary">
                                        You are already friends
                                    </span>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    <% end %>
<% end %>

app/views/friends/_result.js.erb
$('#results').html("<%= j (render 'friends/result.html') %>")