config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "user/registrations"}
  root 'welcome#index'
  
  get 'my_portfolio', to: "users#my_portfolio"
  
  get 'search_stocks', to: "stocks#search"
  
  resources :user_stocks, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :friendships
  
  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
    has_many :user_stocks
    has_many :stocks, through: :user_stocks
    
    has_many :friendships
    has_many :friends, through: :friendships
    
    def full_name
        return "#{first_name} #{last_name}".strip if (first_name || last_name)
        "Anonymous"
    end
  
    def stock_already_added?(ticker_symbol)
        stock = Stock.find_by_ticker(ticker_symbol)
        return false unless stock
        user_stocks.where(stock_id: stock.id).exists?
    end
    
    def under_stock_limit?
        (user_stocks.count < 10)
    end
    
    def can_add_stock?(ticker_symbol)
        under_stock_limit? && !stock_already_added?(ticker_symbol)
    end
    
    def self.search(param)
        param.strip!
        param.downcase!
        to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
        return nil unless to_send_back
        to_send_back
    end
    
    def self.first_name_matches(param)
        matches('first_name', param)
    end
    
    def self.last_name_matches(param)
        matches('last_name', param)
    end
    
    def self.email_matches(param)
        matches('email', param)
    end
    
    def self.matches(field_name, param)
        User.where("#{field_name} like ?", "%#{param}%")
    end
    
    def except_current_user(users)
        users.reject { |user| user.id == self.id }
    end
    
    def not_friends_with?(friend_id)
        friendships.where(friend_id: friend_id).count < 1
    end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
    before_filter :configure_permitted_parameters
    
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def my_portfolio
        @user = current_user
        @user_stocks = current_user.stocks
    end
    
    def my_friends
        @friendships = current_user.friends
    end
    
    def search 
        if params[:search_param].blank?
            flash.now[:danger] = "You have entered an empty search"
        else
            @users = User.search(params[:search_param])
            @users = current_user.except_current_user(@users)
            flash.now[:danger] = "No users match search criteria" if @users.blank?
        end
        respond_to do |format|
            format.js { render partial: 'friends/result' }
        end
    end
    
    def add_friend
        @friend = User.find(params[:friend])
        current_user.friendships.build(friend_id: @friend.id)
        
        if current_user.save 
            flash[:success] = "Friend was successfully added"
        else
            flash[:danger] = "There was something wrong"
        end
        redirect_to my_friends_path
    end
    
    def show
        @user = User.find(params[:id])
        @user_stocks = @user.stocks
    end
end

app/views/users/_result.html.erb
<br><br><br><br>
<% if params[:action] == 'search' %>
<div class="result-block">
    <%= bootstrap_flash %>
</div>
<% end %>
<% if @stock %>
    <div class="well results-block">
        <strong>Symbol:</strong> <%= @stock.ticker %>
        <strong>Name:</strong> <%= @stock.name %>
        <strong>Price:</strong> <%= @stock.last_price %>
        <% if current_user.can_add_stock?(@stock.ticker) %>
            <%= link_to "Add to my stock", user_stocks_path(user: current_user, stock_ticker: @stock.ticker), method: :post, class: "btn btn-primary" %>
        <% else %>
            <span class="label label-default">
                Stock cannot be added because you have already added
                <% if !current_user.under_stock_limit? %>
                    10 Stocks
                <% end %>
                <% if current_user.stock_already_added?(@stock.ticker) %>
                    This stock 
                <% end %>
            </span>
        <% end %>
    </div>
<% end %>

app/views/users/my_friends.html.erb
<%= render "friends/lookup" %>

<% if @friendships.size > 0 %>
    <table class="table table-striped">
        <thead>
            <tr>
                <th colspan="3" class="page-header">
                    <h2>My Friends</h2>
                </th>
            </tr>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @friendships.each do |friend| %>
                <tr>
                    <td><%= friend.full_name %></td>
                    <td><%= friend.email %></td>
                    <td>
                        <%= link_to "View Profile", user_path(friend), class: "btn btn-primary btn-xs" %>
                        <%= link_to "Remove Friend", friendship_path(friend), method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-xs btn-danger" %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% else %>
    <div class="row col-lg-12">
        <p class="lead">You don't have any friends yet. Please add some!</p>
    </div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<h3>Search for Stocks</h3>
<div id="stock-lookup">
    <%= form_tag search_stocks_path, method: :get, remote: true, id: 'stock-lookup-form' do %>
        <div class="from-group row no-padding text-center col-md-12">
            <div class="col-md-10">
                <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticke symbol", autofocus: true, class: 'form-control search-box input-lg' %>
            </div>
            <div class="col-md-2">
                <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
                    <span class="fa fa-search"></span> Look up a stock
                <% end %>
            </div>
        </div>
    <% end %>
</div>

<div id="results">
    <%= render "users/result" %>
</div>
<br><br>
<%= render 'stocks/list' %>

app/views/users/show.html.erb
<h2>User Details</h2>

<dl class="dl-horizontal">
    <dt><strong>Full Name</strong></dt>
    <dd><%= @user.full_name %></dd>
    
    <dt><strong>Email</strong></dt>
    <dd><%= @user.email %></dd>
</dl>

<% if @user.stocks.size > 0 %>
    <%= render 'stocks/list' %>
<% else %>
    <p class="lead">This user is not tracking any stocks</p>
<% end %>

<%= link_to "Back", my_friends_path, class: "btn btn-primary" %>