config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "user/registrations"}
  root 'welcome#index'
  
  get 'my_portfolio', to: "users#my_portfolio"
  
  get 'search_stocks', to: "stocks#search"
  
  resources :user_stocks, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :friendships
  
  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
    <div class="container">
        <a class="navbar-brand" href="/">FinanceTracker</a>
        <% if current_user %>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
            <div class="navbar-collapse collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav col-md-6">
                    <li><%= link_to "My Portfolio", my_portfolio_path  %></li>
                    <li><%= link_to "My Profile", edit_registration_path(current_user)  %></li>
                    <li><%= link_to "My Friends", my_friends_path  %></li>
                </ul>
                <ul class="nav navbar-right col-md-4">
                    <li class="col-md-8 user-name text-right ">
                        <span class="fa fa-user"></span>
                        <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
                    </li>
                    <li class="col-md-4 logout">
                        <%= link_to("Logout", destroy_user_session_path, class: "btn btn-xs btn-danger", method: :delete)  %>
                    </li>
                </ul>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinanceTracker" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
    <body>
        <%= render "layouts/navigation" %>
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <%= bootstrap_flash %>
                    <%= yield %>
                </div>
            </div><!--/row-->
    
            <footer>
                <p>&copy; Company 2017</p>
            </footer>
        </div> <!-- /container -->
    </body>
</html>